AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - script/**/*
    - puppet/**/*
    - tmp/**/*
    - log/**/*

Style/Documentation:
  Enabled: false